#!/bin/bash

set -euo pipefail

H5_DIR="$1"
LOG_DIR="$2"

PARENT=$(dirname $H5_DIR)
EXPERIMENT=$(basename $PARENT)

mkdir -p $LOG_DIR

# combine_and_shuffle $H5_DIR/* "$PARENT/$EXPERIMENT.h5" > "$LOG_DIR"/PRE_run_augmentation.log 2>&1
