#!/bin/bash

set -euo pipefail

NGEN="$1"
DELPHES_DIR="$2"
LD_LIBRARY_PATH="$3"
TEMPDIR="$4"
DELPHES_CARD="$5"
ROOT_FILES_DIR="$6"
LOG_DIR="$7"

export LD_LIBRARY_PATH

FILENAME="$TEMPDIR"/procdir."$NGEN".tmp
PROC_DIR=$(cat $FILENAME | awk '{print $1}')
BASENAME=$(basename $PROC_DIR)
ROOT_FILE_DIR="$ROOT_FILES_DIR"/"$BASENAME"

mkdir -p $ROOT_FILE_DIR

# TODO: Run diagram generation, mc sampling and delphes on the same node (this has to be done sequentially anyway)
# Then transfer only .root files (and lhe files) to a process dir in /dcache
# Use 'environment' in submit files instead of passing variables as script arguments...

PROC_DIR_TMP=$TMP/mgprocess
ROOT_DIR_TMP=$TMP/rootfiles

mkdir -p $PROC_DIR_TMP

# TODO: You don't even need the whole process directory but just lhe and hepmc.gz files...
cp -rv $PROC_DIR/* $PROC_DIR_TMP

madminer --log-file "$LOG_DIR/delphes.log" run_delphes $PROC_DIR_TMP --root-files-dir $ROOT_DIR_TMP --delphes-dir $DELPHES_DIR --delphes-card $DELPHES_CARD

cp -vfr $ROOT_DIR_TMP/* $ROOT_FILE_DIR
